// Code generated by "stringer -output=type_string.go -type=AddrType,CfgLoadType,LoadStatusType"; DO NOT EDIT.

package snmp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AddrIPv4-1]
}

const _AddrType_name = "AddrIPv4"

var _AddrType_index = [...]uint8{0, 8}

func (i AddrType) String() string {
	i -= 1
	if i < 0 || i >= AddrType(len(_AddrType_index)-1) {
		return "AddrType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AddrType_name[_AddrType_index[i]:_AddrType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CfgLoadRunningConfigDownload-22]
}

const _CfgLoadType_name = "CfgLoadRunningConfigDownload"

var _CfgLoadType_index = [...]uint8{0, 28}

func (i CfgLoadType) String() string {
	i -= 22
	if i < 0 || i >= CfgLoadType(len(_CfgLoadType_index)-1) {
		return "CfgLoadType(" + strconv.FormatInt(int64(i+22), 10) + ")"
	}
	return _CfgLoadType_name[_CfgLoadType_index[i]:_CfgLoadType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoadStatusNormal-1]
	_ = x[LoadStatusFlashPrepareReadFailure-2]
	_ = x[LoadStatusFlashReadError-3]
	_ = x[LoadStatusFlashPrepareWriteFailure-4]
	_ = x[LoadStatusFlashWriteError-5]
	_ = x[LoadStatusTftpTimeoutError-6]
	_ = x[LoadStatusTftpOutOfBufferSpace-7]
	_ = x[LoadStatusTftpBusy-8]
	_ = x[LoadStatusTftpRemoteOtherErrors-9]
	_ = x[LoadStatusTftpRemoteNoFile-10]
	_ = x[LoadStatusTftpRemoteBadAccess-11]
	_ = x[LoadStatusTftpRemoteDiskFull-12]
	_ = x[LoadStatusTftpRemoteBadOperation-13]
	_ = x[LoadStatusTftpRemoteBadID-14]
	_ = x[LoadStatusTftpRemoteFileExists-15]
	_ = x[LoadStatusTftpRemoteNoUser-16]
	_ = x[LoadStatusOperationError-17]
	_ = x[LoadStatusLoading-18]
}

const _LoadStatusType_name = "LoadStatusNormalLoadStatusFlashPrepareReadFailureLoadStatusFlashReadErrorLoadStatusFlashPrepareWriteFailureLoadStatusFlashWriteErrorLoadStatusTftpTimeoutErrorLoadStatusTftpOutOfBufferSpaceLoadStatusTftpBusyLoadStatusTftpRemoteOtherErrorsLoadStatusTftpRemoteNoFileLoadStatusTftpRemoteBadAccessLoadStatusTftpRemoteDiskFullLoadStatusTftpRemoteBadOperationLoadStatusTftpRemoteBadIDLoadStatusTftpRemoteFileExistsLoadStatusTftpRemoteNoUserLoadStatusOperationErrorLoadStatusLoading"

var _LoadStatusType_index = [...]uint16{0, 16, 49, 73, 107, 132, 158, 188, 206, 237, 263, 292, 320, 352, 377, 407, 433, 457, 474}

func (i LoadStatusType) String() string {
	i -= 1
	if i < 0 || i >= LoadStatusType(len(_LoadStatusType_index)-1) {
		return "LoadStatusType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LoadStatusType_name[_LoadStatusType_index[i]:_LoadStatusType_index[i+1]]
}
